import * as THREE from "three";
import { OrbitControls } from "./vendor/OrbitControls.js";
import { GLTFLoader } from "./vendor/GLTFLoader.js";

const gridEl=document.getElementById("viewerGrid"),assetNameEl=document.getElementById("assetName"),assetMetaEl=document.getElementById("assetMeta"),modelStatsEl=document.getElementById("modelStats"),viewerStatusEl=document.getElementById("viewerStatus"),overlayToggle=document.getElementById("overlayToggle"),overlayOpacity=document.getElementById("overlayOpacity"),referenceLabel=document.getElementById("referenceLabel"),cameraToggle=document.getElementById("cameraToggle"),gridToggle=document.getElementById("gridToggle"),rotateToggle=document.getElementById("rotateToggle");
const loader=new GLTFLoader();
let stateVersion=null,state=null,viewports=[],layout="single",styleMode="material",projection="perspective",showGrid=true,autoRotate=false,syncLock=false;

function overrideMaterial(mode){if(mode==="clay")return new THREE.MeshStandardMaterial({color:0xb8c2ce,roughness:.9,metalness:0});if(mode==="wire")return new THREE.MeshStandardMaterial({color:0x8dbdff,roughness:.8,wireframe:true});if(mode==="silhouette")return new THREE.MeshBasicMaterial({color:0x000000});if(mode==="normals")return new THREE.MeshNormalMaterial();return null}
function rememberMaterials(root){root.traverse(o=>{if(o.isMesh)o.userData.majdOriginalMaterial=o.material})}
function applyStyle(root){if(!root)return;root.traverse(o=>{if(!o.isMesh)return;if(styleMode==="material"){if(o.userData.majdOriginalMaterial)o.material=o.userData.majdOriginalMaterial}else{o.material=overrideMaterial(styleMode)}})}
function normalizeObject(obj){const box=new THREE.Box3().setFromObject(obj),size=new THREE.Vector3(),center=new THREE.Vector3();box.getSize(size);box.getCenter(center);obj.position.sub(center);const maxDim=Math.max(size.x,size.y,size.z,1e-6);obj.scale.setScalar(2.2/maxDim);const box2=new THREE.Box3().setFromObject(obj);obj.position.y-=box2.min.y+1.05}
function resize(vp){const w=Math.max(1,vp.holder.clientWidth),h=Math.max(1,vp.holder.clientHeight);vp.renderer.setSize(w,h,false);vp.persp.aspect=w/h;vp.persp.updateProjectionMatrix();const a=w/h,s=1.7;vp.ortho.left=-s*a;vp.ortho.right=s*a;vp.ortho.top=s;vp.ortho.bottom=-s;vp.ortho.updateProjectionMatrix()}
function makeViewport(model){const holder=document.createElement("div");holder.className="viewport";const label=document.createElement("div");label.className="label";label.innerHTML=`<b>${model?.label??"Empty"}</b>${model?.score!=null?`${model.score}% · ${model.vertices||0}v · ${model.faces||0}f`:""}`;holder.appendChild(label);const ref=document.createElement("img");ref.className="reference";if(state?.reference)ref.src=state.reference+`?v=${state.version}`;ref.style.opacity=overlayOpacity.value;holder.appendChild(ref);const scene=new THREE.Scene(),persp=new THREE.PerspectiveCamera(36,1,.01,100),ortho=new THREE.OrthographicCamera(-2,2,2,-2,.01,100);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;holder.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x24344a,2.2));const key=new THREE.DirectionalLight(0xffffff,3.4);key.position.set(3,-4,6);scene.add(key);const fill=new THREE.DirectionalLight(0x8ebcff,1.2);fill.position.set(-4,2,2);scene.add(fill);const grid=new THREE.GridHelper(8,24,0x35567c,0x203550);grid.position.y=-1.05;grid.visible=showGrid;scene.add(grid);const root=new THREE.Group();scene.add(root);const camera=projection==="perspective"?persp:ortho;const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.07;const vp={holder,label,ref,scene,persp,ortho,camera,renderer,controls,grid,root,modelRoot:null,model,baseDistance:4};controls.addEventListener("change",()=>{if(layout!=="compare"||syncLock)return;syncFrom(vp)});gridEl.appendChild(holder);if(model?.url)loader.load(model.url+`?v=${state.version}`,g=>{const obj=g.scene;normalizeObject(obj);rememberMaterials(obj);root.add(obj);vp.modelRoot=obj;applyStyle(obj);resetCamera(vp,"threeq");viewerStatusEl.textContent="Loaded"},undefined,e=>{console.error(e);viewerStatusEl.textContent="Failed to load model"});return vp}
function resetCamera(vp,p="threeq"){const d=vp.baseDistance,pos={front:[0,0,d],back:[0,0,-d],left:[-d,0,0],right:[d,0,0],threeq:[d*.75,d*.18,d*.75],top:[0,d,.001],reset:[d*.75,d*.18,d*.75]}[p]||[d*.75,d*.18,d*.75];vp.camera.position.set(...pos);vp.camera.up.set(0,1,0);vp.controls.target.set(0,0,0);vp.camera.lookAt(0,0,0);vp.controls.update()}
function syncFrom(src){syncLock=true;for(const vp of viewports){if(vp===src)continue;vp.camera.position.copy(src.camera.position);vp.camera.quaternion.copy(src.camera.quaternion);vp.controls.target.copy(src.controls.target);if(projection==="orthographic"){vp.camera.zoom=src.camera.zoom;vp.camera.updateProjectionMatrix()}vp.controls.update()}syncLock=false}
function setLayout(v){layout=v;document.querySelectorAll("[data-layout]").forEach(b=>b.classList.toggle("active",b.dataset.layout===v));gridEl.className=v==="compare"?"compare":"single";viewports.forEach((vp,i)=>vp.holder.style.display=(v==="single"?i===0:i<3)?"block":"none");setTimeout(()=>viewports.forEach(resize),20)}
function setStyle(v){styleMode=v;document.querySelectorAll("[data-style]").forEach(b=>b.classList.toggle("active",b.dataset.style===v));viewports.forEach(vp=>applyStyle(vp.modelRoot))}
function switchProjection(){projection=projection==="perspective"?"orthographic":"perspective";cameraToggle.textContent=projection==="perspective"?"Perspective":"Orthographic";for(const vp of viewports){const old=vp.camera,next=projection==="perspective"?vp.persp:vp.ortho;next.position.copy(old.position);next.quaternion.copy(old.quaternion);vp.camera=next;vp.controls.object=next;vp.controls.update()}}
function overlayUpdate(){const on=overlayToggle.checked&&!!state?.reference;viewports.forEach((vp,i)=>{vp.ref.style.display=(on&&i===0)?"block":"none";vp.ref.style.opacity=overlayOpacity.value})}
function rebuild(){viewports.forEach(vp=>{try{vp.renderer.dispose()}catch{}vp.holder.remove()});viewports=[];const models=state?.models||[];for(let i=0;i<Math.min(3,Math.max(models.length,1));i++)viewports.push(makeViewport(models[i]||null));setLayout(layout==="compare"&&models.length>1?"compare":"single");overlayUpdate();if(models.length){const m=models[0];modelStatsEl.textContent=`${state.assetName} · ${m.label} · ${m.score??"—"}% · ${m.vertices??"—"} vertices · ${m.faces??"—"} faces`}else modelStatsEl.textContent="No model loaded"}
async function poll(){try{const r=await fetch(`./data/state.json?t=${Date.now()}`,{cache:"no-store"});if(!r.ok)throw new Error();const n=await r.json();if(n.version!==stateVersion){state=n;stateVersion=n.version;assetNameEl.textContent=n.assetName||"No asset selected";const m=n.meta||{};assetMetaEl.textContent=`${m.project?m.project+" · ":""}${m.style?m.style+" · ":""}${m.assetType||""}${m.engine?" · "+m.engine:""}${m.views?" · "+m.views+" views":""}${m.version?" · v"+String(m.version).padStart(3,"0"):""}${m.status?" · "+m.status:""}`;referenceLabel.textContent=n.referenceLabel||"No reference";rebuild()}}catch{viewerStatusEl.textContent="Viewer state unavailable"}}
function animate(){requestAnimationFrame(animate);for(const vp of viewports){if(autoRotate&&vp.modelRoot)vp.modelRoot.rotation.y+=.004;vp.controls.update();resize(vp);vp.renderer.render(vp.scene,vp.camera)}}
document.querySelectorAll("[data-layout]").forEach(b=>b.onclick=()=>setLayout(b.dataset.layout));document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>viewports.forEach(vp=>resetCamera(vp,b.dataset.view)));document.querySelectorAll("[data-style]").forEach(b=>b.onclick=()=>setStyle(b.dataset.style));cameraToggle.onclick=switchProjection;gridToggle.onclick=()=>{showGrid=!showGrid;gridToggle.classList.toggle("active",showGrid);viewports.forEach(vp=>vp.grid.visible=showGrid)};rotateToggle.onclick=()=>{autoRotate=!autoRotate;rotateToggle.classList.toggle("active",autoRotate)};overlayToggle.onchange=overlayUpdate;overlayOpacity.oninput=overlayUpdate;document.getElementById("fullscreen").onclick=async()=>{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()};window.addEventListener("resize",()=>viewports.forEach(resize));setInterval(poll,900);poll();animate();
